#![allow(clippy::needless_return)]
#![allow(clippy::type_complexity)]
#![no_std]

#[cfg(feature = "alloc")]
extern crate alloc;

/// Re-export of [`libm`], so `no_std` users can reach transcendental functions
/// (`libm::sin`, `libm::exp`, …) without taking their own dependency.
pub use libm;

/// The scalar trait the calculus modules are generic over (implemented for `f32` and `f64`).
pub use numeric::Numeric;

// autogenerated tables used for numerical gaussian integration
pub mod gaussian_tables;

pub mod approximation;
pub mod gaussian_tables;
pub mod numeric;
pub mod numerical_derivative;
pub mod numerical_integration;
pub mod utils;
pub mod vector_field;
